### ISSUE TITLE
AS A system administrator I WANT a key list that includes Ed25519 key files from the SSH directory in my home directory IN ORDER TO understand what keys I have available

### ISSUE THREAD

**Issue by IvanJijon** [digitalautonomy/keymirror#4]

**Comment by piratax007** [comment]
This functionality was implemented in https://github.com/digitalautonomy/keymirror/commit/314811f6f896e15515dfecbe0d6808342c60a03a

**Comment by piratax007** [comment]
After reviewing similar acceptance criteria in #2, we conclude that this story is done.
