### ISSUE TITLE
Resolve question: Should we display public keys from `authorized_keys` in the key list?

### ISSUE THREAD

**Issue by IvanJijon** [digitalautonomy/keymirror#99]

**Comment by olabiniV2** [comment]
After discussion with @ivanjijon and @piratax007, we have decided that this is a useful enough functionality that we want to add stories for it. Exactly when those stories will be played is up to prioritization. 

I'll keep this story in Doing until we have added the stories for this functionality.

**Comment by olabiniV2** [comment]
OK, stories for covering functionality related to `authorized_keys` have been created. They are #101, #102, #103, #104, #105, #106, #107, #108, #109, #110, #111, #112, #113, #114, #115, #116, #117, #118, #119, #120, #121, #122, #123, #124 and #125.

That concludes this story.
